### PR TITLE
Reduce url copypaste in tests 

### PR DESCRIPTION
**Pull request by hybridcattt**
### Goals :soccer:
Improve maintainability of the test suite

### Implementation Details :construction:
I noticed a significant amount of copy-pasted urls throughout the test suite. It makes it hard to change the urls, should it become necessary to migrate to another service or use a locally running version of httpbin. 
This PR introduces a `TestEnvironment` namespace which contains a collection of urls used in the suite. More relevant data can be added under this namespace in the future, if needed.  

### Testing Details :mag:
The tests have been modified in a minor way that doesn't change their behaviour.

### CODE REVIEW

**Comment by hybridcattt** [comment]
I completely understand that covid might have put this on lowest priority. Just want to let you guys know that I'm still on top of this and ready to make tweaks to this PR if needed. @jshier @cnoon

**Comment by jshier** [comment]
@hybridcattt We're in the midst of a big test refactor for Alamofire itself (see [#3215](https://github.com/Alamofire/Alamofire/pull/3215)) as we adopt our own test server. This work is very similar to your work here, though I haven't yet formalized all of the endpoints like you have here. Once we've been able to finish our refactor and deploy it we should be ready to then apply the same refactor to AlamofireImage. This PR could serve as at least part of that refactor once we've finalized our test abstraction. So thanks for your work here, we're getting closer to being able integrate this work.

**Comment by hybridcattt** [comment]
That's cool to hear, thanks for getting back to me 🙌

**Comment by jshier** [comment]
@hybridcattt If you're still interested, our test refactor for Alamofire has been merged and the [Firewalk test server](https://github.com/Alamofire/Firewalk) is available (if unannounced), so this is ready for another look. If you copy over the `TestHelpers.swift` file from Alamofire you can use the `Endpoint` type I created to encapsulate the URLs needed for the tests. Then it's just a matter of adopting the `Endpoint` overloads in the tests.

If you aren't interested or don't have time soon, just let me know and I can take care of this myself.

**Comment by hybridcattt** [comment]
@jshier awesome news. I could take a look within the next couple of weeks. 

How keen are you on copying over `TestHelpers.swift`? On top of reusable url management code, it lists specific paths used in Alamofire (`Endpoint.Path`). In AlamofireImage there's a bunch of resources on hosts other than httpbin, do you imagine continuing to use them or moving them to a local server as well?

If you have a specific vision on how it should be, feel free to take care of it.

**Comment by jshier** [comment]
`Endpoint` can encapsulate any `Host`, so any addition resources can be captured that way. I've also been working to consolidate most of the testing calls into Firewalk so we can ensure reliability and performance. I'll take another look this weekend to see exactly what might be needed. I'll let you know.

**Comment by jshier** [comment]
@hybridcattt I've integrated the Alamofire's `TestHelpers` and added the required `Host`s and `Path`s to handle image testing. I also refactored some of the tests to cover all available image formats. Feel free to take a look at the current state and see if there's anything you feel like doing (or not). I think one improvement that could be made is type safe access to our local resources, in addition to the `Endpoint`s, and the ability to create an `Endpoint` from a local resource. I'd image a very similar API, where we do something like `Resource.jpegImage` or `Resource.image(.jpeg)` and `Endpoint.resource(image(.jpeg))`.

**Comment by jshier** [comment]
BTW, you can install Firewalk by running `brew install alamofire/alamofire/firewalk` and then running it. I like to detach with `firewall &`.

**Comment by hybridcattt** [comment]
@jshier awesome, will have a look 👍

**Pull request closed without merging**
