### PR TITLE
Update podspec to Alamofire 5.0.0-beta.3 in alamofire5 branch

### PR DESCRIPTION
**Pull request by grahamburgsma**
### Goals :soccer:
Make AlamofireImage alamofire5 branch work with Alamofire 5.0.0-beta.3

### Implementation Details :construction:
Updated podspec

### CODE REVIEW

**Comment by jshier** [comment]
Thanks for the PR! I think it would be better to update the `.podspec` and `Cartfile` to allow the automatic update of the Alamofire version, using the `~>` operator in both files. That way we won't need another update unless there's a breaking minimum version.

**Comment by grahamburgsma** [comment]
Good call, made that change @jshier.

**Comment by jhand0867** [comment]
Hey guys,
I’ve a project already working with alamofire 5.0.0 beta-3, will you advise how to integrate alamofireimage 3.5, I’ve not been able to install the pod and the get a message which seem to require to have alamofire 4.8 instead, which means I’ll have to rebuild my project from scratch, most likely change al AF to the old Alamofire. Thanks.

**Comment by grahamburgsma** [comment]
@jhand0867 As a temporary solution you could point to my fork.
`pod 'AlamofireImage', :git => 'https://github.com/grahamburgsma/AlamofireImage.git', :branch => 'alamofire5-beta3'`

@jshier could we get this merged?

**Comment by jshier** [comment]
Sure! Thanks for the PR!

**Pull request merged**
