### PR TITLE
Add heic image type to the image response serializer

### PR DESCRIPTION
**Pull request by taylor-paul**
### Goals :soccer:
The goal is to be able to download heic images without having to ensure that the type is manually added to the image response serializer. Heic is a native format created by Apple that is growing in popularity.

### CODE REVIEW

**Comment by jshier** [comment]
Thanks for the PR! This should be mergeable after you fix the tests.

**Comment by cnoon** [comment]
Should be an easy fix @taylor-paul. They should fail locally.

**Comment by jshier** [comment]
@taylor-paul Additionally, we may need to conditionalize this, as HEIC wasn't available until iOS 11.

**Comment by taylor-paul** [comment]
@jshier great point! You are right. I'm noticing several of the failing tests are related to the redirect tests. Looks like the url that the test is forming is not working properly https://httpbin.org/redirect-to?url=https://httpbin.org/image/png

**Comment by jshier** [comment]
@taylor-paul Let me do a quick PR to disable those and update our CI and we should be good to go.

**Comment by jshier** [comment]
@taylor-paul Tests updated, though some may still be unstable. If you want to merge `master` into your branch the tests can run again.

**Comment by taylor-paul** [comment]
@jshier looks like I had some of the same test failures as you did.

**Comment by jshier** [comment]
@taylor-paul Yeah, looks like we have some flaky tests. Once you add the conditional support for HEIC on the appropriate OS versions I can merge this.

**Review by jshier — APPROVED** [review]
Thanks for this!

**Pull request merged**
