### PR TITLE
Basic SwiftUI support

### PR DESCRIPTION
**Pull request by alexdremov**
### Issue Link :link:
https://github.com/Alamofire/AlamofireImage/issues/430

### Goals :soccer:
- Implement basic SwiftUI view for images lazy download
- Documentation

### Implementation Details :construction:
- Created LazyImage view that loads image from URL and displays placeholder while loading it
- For optimisation and elegant LazyImage instantiation LazyImageDownloader is created

Looking forward to your comments and advices!
Really wanted to make this beautiful framework to support SwiftUI

### CODE REVIEW

**Comment by jshier** [comment]
Thanks for the PR! However, there are a number of improvements that need to be made before we can accept it.

First, it should offer an API surface as similar as possible to the newly added `AsyncImage`. Ideally users would just need to change the type of the view to migrate between the types.

Second, it needs to include API that allows users to progressively customize the underlying image loading behavior. This would start with simply loading a `URL` like `AsyncImage` to being able to take a full `ImageDownloader` instance. 

Third, it should not use `AnyView` but instead embrace generics to allow the placeholder to be fully defined by a `ViewBuilder`.

**Comment by AlexRoar** [comment]
Thanks for the reply!

I'll try to implement what you requested and will notify when it's ready

**Comment by rr-james-hickman** [comment]
@AlexRoar any update on this? Hoping for some native SwiftUI support so we can utilize this library in our app.

**Comment by AlexRoar** [comment]
> @AlexRoar any update on this? Hoping for some native SwiftUI support so we can utilize this library in our app.

No, have not worked on that one. Found side library for lazy images

**Pull request closed without merging**
