### PR TITLE
Added extension to UIButton to  support remote images

### PR DESCRIPTION
**Pull request by jorjuela33**
I am using this library in some personals projects and I noticed about there is not support to set a remote image as a background or image, I ended with this solution for iOS that can help with the [#13](https://github.com/Alamofire/AlamofireImage/issues/13) . I hope it fits the requirements and guidelines of AlamofireImage.

Regards.

### CODE REVIEW

**Comment by cnoon** [comment]
Okay this looks like an awesome start @jorjuela33. I'll spend some time here in the next few days digging through this in detail, but it looks really solid at first glance. The one thing that jumps out at me right now is that the test suite is failing on watchOS. I would guess that there needs to be some checks here for handling the different OSs properly. My guess here is that you probably only want these files included in the iOS framework and test target. Not sure about tvOS...so we should look into that as well.

**Comment by jorjuela33** [comment]
@cnoon I didn't check for the watchOS, I just tested for iOS. But If I can help with something else please let me know. I will be glad.

Regards.

**Comment by cnoon** [comment]
Hi @jorjuela33...thank you so much for all your hard work here. I squashed your two commits into a single one in 5722c336. Then I refactored a few things in 010750da (diff looks much worse than it really was). Then I added accept header tests in 3000c6ff and cancellation tests in 09a4f705. That last commit was pretty important since the previous implementation suffered from the same cancellation bug as the `UIImageView` extension did. Thankfully it's all fixed up and looking really solid.

Thanks again for putting this together. I'll hopefully get everything released tomorrow. 🍻

**Comment by cnoon** [comment]
I would release tonight, but I need to put together a new section in the README for the UIButton extension.

**Comment by jorjuela33** [comment]
Nice! thanks so much to consider this code and I hope to continue contributing 

Cheers

**Pull request closed without merging**
